# Day 12: The N-Body Problem

## Part 1

In [1]:
import numpy as np
import doctest

In [2]:
def init_all(input_str):
    '''
    str -> np.array
    
    read input positions and create a position velocity array
    
    
    '''
    posvel=np.zeros([2,4,3])
    planet=0
    for line in input_str.split("\n"):
        coord=0
        line=line.replace("<","").replace(">","").replace(" ","")
        for val in line.split(","):
            posvel[0,planet,coord]=val[2:]
            coord+=1
        planet+=1

    return posvel

In [3]:
def update_vel(x):
    '''
    nparray -> nparray
    
    On each axis (x, y, and z), the velocity of each moon changes by exactly +1 or -1 to pull the moons together. 
    For example, if Ganymede has an x position of 3, and Callisto has a x position of 5, 
    then Ganymede's x velocity changes by +1 (because 5 > 3) and Callisto's x velocity changes by -1 (because 3 < 5).
    However, if the positions on a given axis are the same, the velocity on that axis does not change for that 
    pair of moons.
    '''
    for this_planet in range(np.size(x,1)):
        for planet in range(np.size(x,1)):
            if (planet == this_planet):
                planet+=1
                continue
            for coord in range(np.size(x,2)):
                if   (x[0,this_planet,coord] < x[0,planet,coord]):
                    x[1,this_planet,coord]+=1
                elif (x[0,this_planet,coord] > x[0,planet,coord]):
                    x[1,this_planet,coord]-=1
                coord+=1
            planet+=1
        this_planet+=1

In [4]:
def update_pos(x):
    '''
    nparray -> nparray
    
    Once all gravity has been applied, apply velocity: simply add the velocity of each moon to its own position. 
    For example, if Europa has a position of x=1, y=2, z=3 and a velocity of x=-2, y=0,z=3, 
    then its new position would be x=-1, y=2, z=6. 
    This process does not modify the velocity of any moon.
    
    '''
    for this_planet in range(np.size(x,1)):
        for coord in range(np.size(x,2)):
            x[0,this_planet,coord] = x[0,this_planet,coord] + x[1,this_planet,coord]

In [5]:
def calc_energy(input):
    '''
    np.array -> int
    
    Then, it might help to calculate the total energy in the system. 
    The total energy for a single moon is its potential energy multiplied by its kinetic energy. 
    A moon's potential energy is the sum of the absolute values of its x, y, and z position coordinates. 
    A moon's kinetic energy is the sum of the absolute values of its velocity coordinates. 
    '''
    energy=0
    for planet in range(np.size(input,1)):
        energy+=np.sum(np.absolute(input[1,planet,:]))*np.sum(np.absolute(input[0,planet,:]))
    return energy

In [6]:
def simulate(numsteps, inputstr):
    '''
    int, str -> dict 
    
    int=num steps to simulate
    str= starting positions of planets
    dict keys= time steps
    dict values = total energy per step
    '''
    myposvel=init_all(inputstr)
    dict_posvel={}
    dict_energy={}
    for i in range(0,numsteps+1):
        prevposvel=myposvel.copy()
        dict_posvel[i]=prevposvel
        update_vel(myposvel)
        update_pos(myposvel)
        dict_energy[i]=calc_energy(dict_posvel[i])
    return dict_energy,dict_posvel

In [7]:
input='''<x=-1, y=0, z=2>
<x=2, y=-10, z=-7>
<x=4, y=-8, z=8>
<x=3, y=5, z=-1>'''

(a_energy, a_posvel) = simulate(10,input)
a_energy[10]

179.0

In [19]:
secinput='''<x=-8, y=-10, z=0>
<x=5, y=5, z=10>
<x=2, y=-7, z=3>
<x=9, y=-8, z=-3>'''
b,c=simulate(10000,secinput)
b[100]

1940.0

In [16]:
puzinput='''<x=-6, y=-5, z=-8>
<x=0, y=-3, z=-13>
<x=-15, y=10, z=-11>
<x=-3, y=-8, z=3>'''
d,e=simulate(1000000,puzinput)

In [13]:
e[0][:,3,:]

array([[-3., -8.,  3.],
       [ 0.,  0.,  0.]])

In [31]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
for i in range(len(c)):
    #if e[i][1,:,:] == np.zeros([4,3]):
    for planet in range(4):
        if (np.all(c[i][:,planet,:] == c[0][:,planet,:])):
            print(planet, i)

0 0
1 0
2 0
3 0


In [29]:
c[630][:,planet,:]

array([[ -6., -64.,  43.],
       [ 11.,  -8.,  14.]])

In [60]:
np.zeros([1,3])

array([[0., 0., 0.]])

In [15]:
np.lcm.reduce?